<?php
  // Set up page title:
  $pageTitle = $this->newList ? 'Create a List' : "edit_list";
  $this->headTitle($this->translate($pageTitle));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li>' . $this->transEsc($pageTitle) . '</li>';
?>

<?=$this->flashmessages()?>

<?php if ($this->auth()->isLoggedIn() && $this->layout()->getTemplate() !== 'layout/lightbox') :?>
  <div class="<?=$this->layoutClass('mainbody')?>">
  <a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" aria-label="<?=$this->transEsc('sidebar_expand')?>">
      <?=$this->transEsc('Your Account') ?>
  </a>
<?php endif; ?>

<h2><?=$this->transEsc($pageTitle); ?></h2>

<form class="form-edit-list" method="post" name="<?=$this->newList ? 'newList' : 'editListForm'?>">
  <input type="hidden" name="id" value="<?=empty($this->list->id) ? 'NEW' : $this->escapeHtmlAttr($this->list->id) ?>">
  <div class="form-group">
    <label class="control-label" for="list_title"><?=$this->transEsc('List'); ?>:</label>
    <input id="list_title" class="form-control" type="text" name="title" value="<?=isset($this->list['title']) ? $this->escapeHtml($this->list['title']) : ''?>">
  </div>
  <div class="form-group">
    <label class="control-label" for="list_desc"><?=$this->transEsc('Description') ?></label>
    <textarea id="list_desc" class="form-control" name="desc" rows="3"><?=isset($this->list['description']) ? $this->escapeHtml($this->list['description']) : ''?></textarea>
  </div>
  <?php if ($this->usertags()->getListMode() === 'enabled'): ?>
    <div class="form-group">
      <label class="control-label" for="list_tags"><?=$this->transEsc('Tags') ?>:</label>
      <input type="text" name="tags" id="list_tags" class="form-control" value="<?=$this->escapeHtmlAttr($this->listTags)?>">
      <span class="help-block"><?=$this->transEsc("add_tag_note") ?></span>
    </div>
  <?php endif; ?>
  <?php if ($this->userlist()->getMode() === 'public_only'): ?>
    <input type="hidden" name="public" value="1">
  <?php elseif ($this->userlist()->getMode() === 'private_only'): ?>
    <input type="hidden" name="public" value="0">
  <?php else: ?>
    <div class="form-group">
      <label class="control-label"><?=$this->transEsc('Access') ?></label>
      <div class="radio inline">
        <label>
          <input id="list_public_1" type="radio" name="public" value="1"<?php if ($this->list->isPublic()): ?> checked="checked"<?php endif; ?>> <?=$this->transEsc('Public') ?>
        </label>
      </div>
      <div class="radio inline">
        <label>
          <input id="list_public_0" type="radio" name="public" value="0"<?php if (!$this->list->isPublic()): ?> checked="checked"<?php endif; ?>> <?=$this->transEsc('Private') ?>
        </label>
      </div>
    </div>
  <?php endif; ?>
  <hr/>
  <h3><?=$this->transEsc('SemesterApparatus') ?></h3>
  <div class="form-group">
    <label class="control-label"><?=$this->transEsc('SemesterApparatus') ?></label>
    <div class="checkbox inline">
      <label>
        <input id="list_semesterApparatus_checkbox" type="checkbox" name="semesterApparatus" <?php if ($this->list->isSemesterApparatus()): ?> checked="checked"<?php endif; ?>> <?=$this->transEsc('isSemesterApparatus') ?>
      </label>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label" for="seminarTitle"><?= $this->transEsc('Seminar Title') ?>:</label>
    <input id="seminarTitle" class="form-control" type="text" name="seminarTitle"
           value="<?= isset($this->list['seminarTitle']) ? $this->transEsc($this->list['seminarTitle']) : '' ?>">
  </div>
  <div class="form-group">
    <label class="control-label" for="nameOfLecturer"><?= $this->transEsc('Name of Lecturer') ?>:</label>
    <input id="nameOfLecturer" class="form-control" type="text" name="nameOfLecturer"
           value="<?= isset($this->list['nameOfLecturer']) ? $this->transEsc($this->list['nameOfLecturer']) : '' ?>">
  </div>
  <div class="form-group">
    <label class="control-label" for="linkToMoodle"><?= $this->transEsc('Link to Moodle') ?>:</label>
    <input id="linkToMoodle" class="form-control" type="text" name="linkToMoodle"
           value="<?= isset($this->list['linkToMoodle']) ? $this->transEsc($this->list['linkToMoodle']) : '' ?>">
  </div>
  <div class="form-group">
    <label class="control-label" for="seminarTitle"><?= $this->transEsc('Semester Apparatus Campus Location') ?>
      :</label><br/>
    <select name="location" id="location">
        <?php foreach ($this->semesterApparatusLocations as $semesterApparatusLocation): ?>
          <option value="<?= $this->escapeHtmlAttr($semesterApparatusLocation) ?>" <?= isset($this->list['location']) && $this->list['location'] === $semesterApparatusLocation ? 'selected' : '' ?>><?= $this->transEsc($semesterApparatusLocation) ?></option>
        <?php endforeach; ?>
    </select>
  </div>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr('Save') ?>">
  </div>
</form>
<?php if ($this->auth()->isLoggedIn() && $this->layout()->getTemplate() !== 'layout/lightbox') :?>
  </div>
  <div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
      <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => empty($this->list->id) ? 'editlist/NEW' : 'list' . $this->list->id])?>
  </div>
<?php endif; ?>
