<?php
  // Set up page title:
  $this->headTitle($this->translate('Edit') . ' : ' . $this->driver->getBreadcrumb());

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . (
        isset($listID)
          ? '<li><a href="' . $this->url('userList', ['id' => $listID]) . '">' . $this->transEsc('List') . '</a></li>'
          : '<li><a href="' . $this->url('myresearch-favorites') . '">' . $this->transEsc('Favorites') . '</a></li>'
    ) . '<li class="active">' . $this->transEsc('Edit') . '</li>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <a class="search-filter-toggle visible-xs" href="#myresearch-sidebar"
    data-toggle="offcanvas" aria-label="<?=$this->transEsc('sidebar_expand')?>">
    <?=$this->transEsc('Your Account') ?>
  </a>

  <h2><?=$this->escapeHtml($this->driver->getBreadcrumb())?></h2>

  <form class="form-list-edit" method="post" name="editForm">
  <?php if (empty($this->savedData)): ?>
    <p class="alert alert-info">
      <?php if (isset($listID)): ?>
        <?=$this->transEsc('The record you selected is not part of the selected list.') ?>
      <?php else: ?>
        <?=$this->transEsc('The record you selected is not part of any of your lists.') ?>
      <?php endif; ?>
    </p>
  <?php else: ?>
    <div class="list-edit-container">
      <?php foreach ($this->savedData as $i => $current): ?>
        <fieldset class="list-edit-group">
          <h3><?=$this->transEsc('List') ?>: <?=$this->escapeHtml($current['listTitle'])?></h3>
          <input type="hidden" name="lists[]" value="<?=$this->escapeHtmlAttr($current['listId']) ?>">
          <?php if ($this->usertags()->getMode() !== 'disabled'): ?>
            <div class="form-group">
              <label class="control-label" for="edit_tags<?=$current['listId'] ?>"><?=$this->transEsc('Tags') ?>:</label>
              <input type="text" name="tags<?=$current['listId'] ?>" id="edit_tags<?=$current['listId'] ?>" class="form-control" value="<?=$this->escapeHtmlAttr($current['tags'])?>">
              <span class="help-block"><?=$this->transEsc("add_tag_note") ?></span>
            </div>
          <?php endif; ?>
          <div class="form-group">
            <label class="control-label" for="edit_notes<?=$current['listId'] ?>"><?=$this->transEsc('Notes') ?>:</label>
            <textarea class="form-control" id="edit_notes<?=$current['listId'] ?>" name="notes<?=$current['listId'] ?>" rows="3"><?=$this->escapeHtml($current['notes'])?></textarea>
          </div>

          <div class="form-group">
            <label class="control-label" for="annotationStudents"><?= $this->transEsc('Annotation Students') ?>:</label>
            <input id="annotationStudents" class="form-control" type="text" name="annotationStudents"
                   value="<?= isset($current['annotationStudents']) ? $this->escapeHtml($current['annotationStudents']) : '' ?>">
          </div>
          <div class="form-group">
            <label class="control-label" for="annotationStaff"><?= $this->transEsc('Annotation Staff') ?>:</label>
            <input id="annotationStaff" class="form-control" type="text" name="annotationStaff"
                   value="<?= isset($current['annotationStaff']) ? $this->escapeHtml($current['annotationStaff']) : '' ?>">
          </div>

          <div class="form-group">
            <label class="control-label" for="scanStatus"><?= $this->transEsc('Scan Status') ?>
              :</label><br/>
            <select name="scanStatus" id="scanStatus">
                <option value="" selected><?= $this->escapeHtml('Select item Scan Status') ?></option>
                <?php foreach ($this->semesterApparatusScanStatuses as $semesterApparatusScanStatus): ?>
                  <option value="<?= $this->escapeHtmlAttr($semesterApparatusScanStatus) ?>" <?= isset($current['scanStatus']) && $current['scanStatus'] === $semesterApparatusScanStatus ? 'selected' : '' ?>><?= $this->escapeHtml($semesterApparatusScanStatus) ?></option>
                <?php endforeach; ?>
            </select>
          </div>

          <?php if($this->isPhysicalFormat): ?>
            <?php if($this->SemesterApparatus()->isLecturer()): ?>
            <div class="form-group">
              <label class="control-label" for="physicalAvailable"><?= $this->transEsc('Physical Available') ?>
                :</label><br/>
              <select name="physicalAvailable" id="physicalAvailable">
                <option value="" <?= !isset($current['physicalAvailable']) ? 'selected' : '' ?>><?= $this->escapeHtml('Select physical Availability') ?></option>
                <option value="1" <?= isset($current['physicalAvailable']) && $current['physicalAvailable'] ? 'selected' : '' ?>><?= $this->escapeHtml('Is physical available') ?></option>
                <option value="0" <?= isset($current['physicalAvailable']) && !$current['physicalAvailable'] ? 'selected' : '' ?>><?= $this->escapeHtml('Is not physical available') ?></option>
              </select>
            </div>
            <?php endif; ?>
              <?php if($this->SemesterApparatus()->isLibrary()): ?>
              <div class="form-group">
                <label class="control-label" for="orderStatus"><?= $this->transEsc('Order status') ?>
                  :</label><br/>
                <select name="orderStatus" id="orderStatus">
                  <option value="" <?= !isset($current['orderStatus']) ? 'selected' : '' ?>><?= $this->escapeHtml('Select Order Status') ?></option>
                  <option value="1" <?= isset($current['orderStatus']) && ($current['orderStatus'] == '1') ? 'selected' : '' ?>><?= $this->escapeHtml('Is Ordered') ?></option>
                  <option value="2" <?= isset($current['orderStatus']) && ($current['orderStatus'] == '2') ? 'selected' : '' ?>><?= $this->escapeHtml('Is Available') ?></option>
                </select>
              </div>
              <?php endif; ?>
          <?php endif; ?>

          <a class="icon-link" href="<?=$this->url('userList', ['id' => $current['listId']]) ?>?delete=<?=urlencode($this->driver->getUniqueId())?>&amp;source=<?=urlencode($this->driver->getSourceIdentifier())?>" id="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>delete<?=$current['listId'] ?>" data-lightbox>
            <?=$this->icon('user-list-delete', 'icon-link__icon') ?>
            <span class="icon-link__label"><?=$this->transEsc('Delete') ?></span>
          </a>
        </fieldset>
      <?php endforeach; ?>
    </div>
  <?php endif; ?>
  <?php if (count($this->lists) > 0): ?>
    <hr>
    <div class="form-group">
      <select name="addToList" class="form-control">
        <option value="-1">- <?=$this->transEsc('Add to another list')?> -</option>
        <?php foreach ($this->lists as $listID => $listTitle): ?>
          <option value="<?=$this->escapeHtmlAttr($listID) ?>"><?=$this->escapeHtml($listTitle) ?></option>
        <?php endforeach; ?>
      </select>
    </div>
  <?php endif; ?>
  <?php if (!empty($this->savedData) || count($this->lists) > 0): ?>
    <div class="form-group">
      <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr('Save') ?>">
    </div>
  <?php endif; ?>
  </form>
</div>
<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => empty($listID) ? 'favorites' : 'list' . $listID])?>
</div>
