<?php if($this->list->semesterApparatus): ?>
  <div class="semester-apparatus-entry">
    <?php foreach ($this->savedData as $data): ?>
      <?php if($data['record_id'] == $this->id): ?>
        <?php if(isset($data['annotationStudents']) && !empty($data['annotationStudents'])): ?>
          <b><?=$this->transEsc('Semester Apparatus Annotation Students')?>:</b> <span><?=$data['annotationStudents']?></span><br/>
        <?php endif; ?>

        <?php if(($this->SemesterApparatus()->isLecturer() || $this->SemesterApparatus()->isLibrary()) && isset($data['annotationStaff']) && !empty($data['annotationStaff'])): ?>
          <b><?=$this->transEsc('Semester Apparatus Annotation Staff')?>:</b> <span><?=$data['annotationStaff']?></span><br/>
        <?php endif; ?>

        <?php if(isset($data['orderStatus']) && !empty($data['orderStatus'])): ?>
          <?php if($data['orderStatus'] == '1'): ?>
            <b><?=$this->transEsc('Semester Apparatus Order Status')?>:</b> <span><?=$this->transEsc('ordered')?></span><br/>
        <?php elseif($data['orderStatus'] == '2'): ?>
            <b><?=$this->transEsc('Semester Apparatus Order Status')?>:</b> <span><?=$this->transEsc('available')?></span><br/>
          <?php endif; ?>
        <?php endif; ?>
      <?php endif ?>
    <?php endforeach ?>
  </div>
<?php endif;